/*
 * AppReducer
 *
 * The reducer takes care of our data. Using actions, we can
 * update our application state. To add a new action,
 * add it to the switch statement in the reducer function
 *
 */

import produce from 'immer';
import { LOAD_GIGS_SUCCESS, LOAD_GIGS, LOAD_GIGS_ERROR } from './constants';
import rlac from './img/rlac.png';
import rover from './img/rover.jpg';
import uber from './img/uber.png';
import neighbor from './img/neighbor.png';
import taskrabbit from './img/taskrabbit.png';
import roadie from './img/roadie.png';
import instacart from './img/instacart.png';
import lyft from './img/lyft.png';
import amazon from './img/amazon.png';
import airbnb from './img/airbnb.png';
import postmates from './img/postmates.png';
import doordash from './img/doordash.png';
import wag from './img/wag.png';
import ubereats from './img/ubereats.png';
import turo from './img/turo.png';
import getaround from './img/getaround.png';
import handy from './img/handy.png';
// Services
import gridwise from './img/gridwise.png';
import mystro from './img/mystro.jpg';
import surge from './img/surge.png';

// The initial state of the App
export const initialState = {
  loading: false,
  error: false,
  userData: {
    gigs: [
      // Gigs
      //
      //
      //    Driving Gigs
      {
        id: 'G0001', // Rideshare
        logo: uber,
        gig: 'Uber Driver',
        description:
          'The taxi of the 21st century. Drive around town, picking up and dropping off passengers.',
        indeed: 'https://www.indeed.com/cmp/Uber/reviews',
        promo:
          'Sign Up With Promo Code PRGREY and Get $20 When You Complete a Trip',
        gigsite: 'uber.com/drive/',
        featured: true,
        type: 'gig',
      },
      {
        id: 'G0009',
        logo: lyft,
        gig: 'Lyft Driver',
        description:
          'Lyft is a ridesharing app. Get paid to drive passengers around town',
        indeed: 'https://www.indeed.com/cmp/Lyft/reviews',
        promo: '',
        gigsite: 'https://www.lyft.com/drive-with-lyft',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0037',
        logo: uber,
        gig: 'HopSkipDrive',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0039',
        logo: uber,
        gig: 'Juno',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0054',
        logo: uber,
        gig: 'Wingz',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0163',
        logo: uber,
        gig: 'GroundLink Chauffeur',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0007', // Delivery
        logo: roadie,
        gig: 'Roadie Driver', // Last mile
        description:
          'Going on a roadtrip soon? Roadie will pay you to fill your empty space and complete deliveries on the way',
        indeed: 'https://www.indeed.com/cmp/Roadie/reviews',
        promo: '',
        gigsite: 'https://my.roadie.com/drive/sign-up/basic-info',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0010',
        logo: amazon,
        gig: 'Amazon Flex Driver',
        description:
          'Perform the "last mile" of Amazon delivery, moving packages from regional centers to customers.',
        indeed: 'https://www.indeed.com/cmp/Amazon.com/reviews?fcountry=ALL',
        promo: '',
        gigsite: 'https://flex.amazon.com/',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0143',
        logo: uber,
        gig: 'Skipcart',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0155',
        logo: uber,
        gig: 'PICKUP',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0157',
        logo: uber,
        gig: 'TommyRun',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0161',
        logo: uber,
        gig: 'uShip',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0013',
        logo: postmates, // Food
        gig: 'Postmates Courier',
        description:
          'Postmates drivers earn a living by delivering food, convenience items, and small office goods to local consumers.',
        indeed: 'https://www.indeed.com/cmp/Postmates/reviews',
        promo: '',
        gigsite: 'https://fleet.postmates.com/',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0014',
        logo: doordash,
        gig: 'DoorDash Dasher',
        description:
          'Doordash is a food delivery app that employs Dashers to Deliver goods.',
        indeed: 'https://www.indeed.com/cmp/Doordash/reviews',
        promo: '',
        gigsite: 'https://www.doordash.com/dasher/signup/',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0016',
        logo: ubereats,
        gig: 'Uber Delivery Driver',
        description:
          'UberEats drivers pick up food from local restaurants and deliver the orders to customers.',
        indeed:
          'https://www.indeed.com/cmp/Uber-Partner-Drivers/reviews?fjobtitle=Delivery+Driver',
        promo: '',
        gigsite: 'https://www.uber.com/a/signup/drive/deliver/',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0034',
        logo: uber,
        gig: 'Grubhub',
        description:
          'A food delivery service, similar to DoorDash and other options on this website.',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0024',
        logo: uber,
        gig: 'Caviar',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0030',
        logo: uber,
        gig: 'Favor',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0144',
        logo: uber,
        gig: 'Hungr',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0148',
        logo: uber,
        gig: 'Zifty Driver',
        description:
          'Delivery drivers. Zifty is an online delivery company that partners with local restaurants and brands to bring their goods straight to clients’ doors. Zifty is looking for enthusiastic delivery providers to make deliveries of food, movies, and other items to customers. ',
        indeed: '',
        promo: '',
        gigsite: 'http://jobs.zifty.com/',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0008', // Shopping
        logo: instacart,
        gig: 'Instacart Shopper',
        description:
          'Shoppers are independent contractors that use the Instacart platform to shop and deliver orders for their customers.',
        indeed: 'https://www.indeed.com/cmp/Instacart/reviews',
        promo: '',
        gigsite: 'https://shoppers.instacart.com/',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0046',
        logo: uber,
        gig: 'Shipt',
        description:
          'Delivering groceries, home products, and some electronics for a company owned by Target.',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      //
      //
      //    Property (Rental) Gigs
      {
        id: 'G0002', // Home rentals
        logo: rlac,
        gig: 'Rent Like a Champion',
        description:
          'AirBnb for sporting events! Rent your home out to eager fans traveling for games in your hometown.',
        indeed: 'https://www.trustpilot.com/review/rentlikeachampion.com',
        promo:
          'Sign Up With Promo Code XXXXX and Get $20 After Your First Rental',
        gigsite: 'https://rentlikeachampion.com/',
        featured: true,
        type: 'gig',
      },
      {
        id: 'G0004',
        logo: neighbor,
        gig: 'Neighbor Storage',
        description:
          'Earn money by giving your empty storage space a job. Rent out your basement, garage and even closets!',
        indeed: 'https://www.trustpilot.com/review/neighbor.com',
        promo: 'Sign Up Through the Link Below and Get $50!',
        gigsite: 'https://www.neighbor.com/invited/nextwrk-39640',
        featured: true,
        type: 'gig',
      },
      {
        id: 'G0012',
        logo: airbnb,
        gig: 'AirBnB Host',
        description:
          'Rent out your home and/or rooms to travelers. AirBnB gives you full control of your availability, prices and house rules.',
        indeed: 'https://www.indeed.com/cmp/Airbnb/reviews',
        promo: '',
        gigsite: 'https://www.airbnb.com/host/homes',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0036',
        logo: uber,
        gig: 'HomeAway',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0041',
        logo: uber,
        gig: 'onefinestay',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0053',
        logo: uber,
        gig: 'VRBO',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0017', // Car rentals
        logo: turo,
        gig: 'Turo Car Rental',
        description:
          'Instead of leaving your car in the garage all day, rent it out! Turo is a car rental service that connects renters with car owners.',
        indeed: 'https://www.trustpilot.com/review/turo.com',
        promo: '',
        gigsite: 'https://turo.com/us/en/list-your-car',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0018',
        logo: getaround,
        gig: 'Getaround Car Rental',
        description:
          'Instead of leaving your car in the garage all day, rent it out! Getaround is a car rental service that connects renters with car owners.',
        indeed: 'https://www.yelp.com/biz/getaround-san-francisco',
        promo: '',
        gigsite: 'https://www.getaround.com/list',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0049', // Parking Rental
        logo: uber,
        gig: 'SpotHero',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0058',
        logo: uber,
        gig: 'ParkingPanda',
        description:
          'A parking space is a premium product in many major cities across the country. ParkingPanda is an app that brings owners and customers together seamlessly. You can post a free listing with the app to start earning cash whenever anyone books your space.',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0025', // Other rental
        logo: uber,
        gig: 'Closet Collective',
        description:
          'Are you a fashionista with a closet full of designer clothes? If so, Closet Collective will provide the venue for renting your $200 plus designer pieces.',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0042',
        logo: uber,
        gig: 'OpenAirplane',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0045',
        logo: uber,
        gig: 'Rentah',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0057',
        logo: uber,
        gig: 'ToolLocker',
        description:
          'Whether you have light or heavy equipment, ToolLocker lets you rent them with a great user interface that filters equipment by category, availability, location and more.',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0066',
        logo: uber,
        gig: 'RVShare',
        description: 'A site that lets you rent out your RV',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0067',
        logo: uber,
        gig: 'Boatsetter',
        description:
          'If you own a boat, then Boatsetter lets you rent it out — either with or without a captain.',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      //
      //
      // Scooter Chargers
      {
        id: 'G0153',
        logo: uber,
        gig: 'Bird Scooter Charger',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      //
      //
      //    Dog Walking Gigs
      {
        id: 'G0003',
        logo: rover,
        gig: 'Rover Walker',
        description:
          'Love animals? Get paid to watch dogs as a Sitter or walk dogs as a Walker through Rover!',
        indeed:
          'https://www.indeed.com/cmp/Rover.com/reviews?fcountry=ALL&fjobtitle=Dog+Walker',
        promo: 'Sign Up Through the Link Below and Get $20!',
        gigsite: 'http://share.rover.com/SWhzJ',
        featured: true,
        type: 'gig',
      },
      {
        id: 'G0015',
        logo: wag,
        gig: 'Wag Walker',
        description:
          'Wag! is the #1 dog walking app to book a dog walker on-demand, or at your convenience.',
        indeed: 'https://www.indeed.com/cmp/Wag!-1/reviews',
        promo: '',
        gigsite: 'https://wagwalking.com/dog-walker',
        featured: false,
        type: 'gig',
      },
      //
      //
      //    Anybody can do it labor
      {
        id: 'G0005', // Manual labor
        logo: taskrabbit,
        gig: 'TaskRabbit Tasker',
        description:
          'TaskRabbit is a marketplace that matches freelance labor with local demand. Get paid to help with everyday tasks, like cleaning, moving, delivery and handyman work',
        indeed: 'https://www.indeed.com/cmp/Taskrabbit/reviews',
        promo: '',
        gigsite:
          'https://support.taskrabbit.com/hc/en-us/articles/360031918292-How-Do-I-Become-a-Tasker-',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0020',
        logo: handy,
        gig: 'Handy Worker',
        description:
          'Handy pays for being a home cleaner and handymen. It covers over 20 cities in North America, Canada, and the UK.',
        indeed: 'https://www.indeed.com/cmp/Handy/reviews',
        promo: '',
        gigsite: 'https://www.handy.com/apply',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0021',
        logo: uber,
        gig: 'Wonolo',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0022',
        logo: uber,
        gig: 'Bellhops',
        description:
          'Get paid to pack boxes and move people into their new digs.',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0027',
        logo: uber,
        gig: 'Dolly',
        description:
          'The Dolly service uses people that have vehicles for moving, or movers to do the heavy lifting if they don’t have a vehicle. ',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0151',
        logo: uber,
        gig: 'GoShare Delivery',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0050',
        logo: uber,
        gig: 'Takl',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0051', // Lawn Care
        logo: uber,
        gig: 'TaskEasy',
        description:
          'TaskEasy freelancers offer lawnmowing, gardening, and landscaping services.',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0149',
        logo: uber,
        gig: 'LawnStarter',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0150',
        logo: uber,
        gig: 'Plowz and Mowz',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0152',
        logo: uber,
        gig: 'Lawn Love',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0162', // Cleaning
        logo: uber,
        gig: 'Homeaglow',
        description: '',
        indeed: 'https://www.indeed.com/cmp/Homeaglow/reviews',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0023', // Less intensive labor
        logo: uber,
        gig: 'Care.com', // Childcare
        description:
          'Primarily a place to find work in child or pet care, Care.com also offers gigs for housekeepers, gardeners, tutors, and those caring for the elderly.',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0061',
        logo: uber,
        gig: 'Helpr',
        description:
          'An app that connects parents with reliable childcare help (i.e., babysitting), Helpr is ideal for those with relevant experience looking for occasional part-time work.',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0154',
        logo: uber,
        gig: 'UrbanSitter',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      //
      //
      // Technical gigs
      {
        id: 'G0026',
        logo: uber,
        gig: 'Figure Eight',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0035',
        logo: uber,
        gig: 'HelloTech',
        description:
          'HelloTech gives experts in the tech industry a platform to provide services for individuals in their homes and businesses. ',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0159',
        logo: uber,
        gig: 'iCracked',
        description:
          'Phone repair. iCracked provides local on-demand iPhone, iPad, and Galaxy repair services. iCracked specializes in on-site screen replacements.',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      //
      //
      // Artsy Gigs
      {
        id: 'G0028',
        logo: uber,
        gig: 'Etsy',
        description:
          'Etsy provides a marketplace for people to sell their handmade, vintage, or creative goods online.',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      //
      //
      // Virtual Assistant Gigs
      {
        id: 'G0029',
        logo: uber,
        gig: 'Fancy Hands',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      //
      //
      // Cooking Gigs
      {
        id: 'G0031',
        logo: uber,
        gig: 'Feastly',
        description:
          'If you are a chef and want to host meals and you are a foodie looking for great chef, Feastly is a platform that brings them both together. ',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      //
      //
      // Mystery Shoppers
      {
        id: 'G0033',
        logo: uber,
        gig: 'Gigwalk',
        description:
          'Work for Gigwalk usually involves gathering data for companies about their products and stores. For example, you might be checking what’s on the shelves in a particular shop, and whether it’s correctly priced and labeled.',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0069',
        logo: uber,
        gig: 'Secret Shopper',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0070',
        logo: uber,
        gig: 'Market Force',
        description:
          'At Market Force, you’ll complete mystery shops for banks, restaurants, and stores in order to help those businesses thrive.',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0071',
        logo: uber,
        gig: 'GBW',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0072',
        logo: uber,
        gig: 'Pinnacle',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0073',
        logo: uber,
        gig: 'A Closer Look',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0074',
        logo: uber,
        gig: 'Quest for the Best',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0075',
        logo: uber,
        gig: 'Intellishop',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0076',
        logo: uber,
        gig: 'Perception Strategies',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0077',
        logo: uber,
        gig: 'Sinclair Customer Metrics',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0078',
        logo: uber,
        gig: 'Call Center QA',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0079',
        logo: uber,
        gig: 'ARC Consulting',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      // Bullshit work
      {
        id: 'G0048',
        logo: uber,
        gig: 'Spare5',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0147',
        logo: uber,
        gig: 'Census Taker',
        description: '',
        indeed: '',
        promo: '',
        gigsite:
          'https://recruitment.2020census.gov/ats/careersite/createprofilelite.aspx?c=census&site=1',
        featured: false,
        type: 'gig',
      },
      // Mechanics
      {
        id: 'G0055',
        logo: uber,
        gig: 'YourMechanic',
        description:
          'Providing car repairs and maintenance carried out at customers’ homes, YourMechanic is a way for people with auto repair skills to leverage the gig economy.',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      // Massages
      {
        id: 'G0056',
        logo: uber,
        gig: 'Zeel',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0064',
        logo: uber,
        gig: 'Soothe',
        description:
          'Gig work for massage therapists, including deep tissue, sports, and couples massage work. ',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      // Beauty
      {
        id: 'G0160',
        logo: uber,
        gig: 'Priv',
        description:
          'Beauty. Priv connects customers on-demand with freelance beauty and wellness professionals, taking a 20% commission. Priv services include makeup, blowout, haircut, nails/manicure, massage, personal training, men’s grooming, spray tan and facials. “Priv Pros” select shifts and kinds of jobs they choose.',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      // Manufacturing
      {
        id: 'G0142',
        logo: uber,
        gig: 'Veryable',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      // Nurses
      {
        id: 'G0156',
        logo: uber,
        gig: 'SnapNurse',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      //
      //
      //
      //
      //
      // Unsorted (need to be sorted)
      {
        id: 'G0164',
        logo: uber,
        gig: 'EasyMove',
        description: '',
        indeed: '',
        promo: '',
        gigsite: 'https://geteasymove.com/',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0165',
        logo: uber,
        gig: 'Lime Juicer',
        description: 'charge lime scooter',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0166',
        logo: uber,
        gig: 'Pet Sitters International',
        description: '',
        indeed: '',
        promo: '',
        gigsite: 'https://www.petsit.com/',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0167',
        logo: uber,
        gig: 'SitterCity',
        description: 'Babysitters',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0168',
        logo: uber,
        gig: 'Zum',
        description: 'Child rideshare',
        indeed: '',
        promo: '',
        gigsite: 'https://www.ridezum.com/',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0169',
        logo: uber,
        gig: 'GoPuff',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0170',
        logo: uber,
        gig: 'DeLiv',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0171',
        logo: uber,
        gig: 'Doorman',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0172',
        logo: uber,
        gig: 'Booking.com',
        description: 'Home thing, they have affiliate',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0173',
        logo: uber,
        gig: 'VacationRentals',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0174',
        logo: uber,
        gig: 'Jump Scooter Charger',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0175',
        logo: uber,
        gig: 'Spin Scooter Charger',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0176',
        logo: uber,
        gig: 'Skip Scooter Charger',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0177',
        logo: uber,
        gig: 'Hyrecar',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0178',
        logo: uber,
        gig: 'Slingshot Health',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0179',
        logo: uber,
        gig: 'Heal.com',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0180',
        logo: uber,
        gig: 'Fetch MD',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0181',
        logo: uber,
        gig: '',
        description: 'Deliveroo',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0182',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0183',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0184',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0185',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0186',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0187',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0188',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0189',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0190',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0191',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0192',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0193',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0194',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0195',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      //
      //
      //
      //
      // Services
      {
        id: 'S0001',
        logo: gridwise,
        gig: 'Gridwise',
        description:
          'Gridwise is an intelligence platform which provides information on ridesharing insights to customers, including both rideshare and taxi drivers, to help drivers improve efficiency and profits on the road.',
        indeed:
          'https://appgrooves.com/app/gridwise-earn-more-by-driving-smarter-by-swerv-technologies-llc/negative',
        promo: '',
        gigsite: 'https://gridwise.io/',
        featured: true,
        type: 'service',
      },
      {
        id: 'S0002',
        logo: mystro,
        gig: 'Mystro',
        description:
          'Mystro is an app that orchestrates incoming passenger requests between the Uber and Lyft rideshare apps, so you can stop clicking back and forth',
        indeed:
          'https://play.google.com/store/apps/details?id=partners.driver.mystro&hl=en_US',
        promo: '',
        gigsite: 'https://mystrodriver.com/download',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0003',
        logo: surge,
        gig: 'Surge 2x',
        description:
          'By using Surge you are able to only drive during surges. You will be able to out perform other top drivers in your city, drastically increasing your profit.',
        indeed: 'https://apps.apple.com/us/app/surge-2x/id986581500',
        promo: '',
        gigsite: 'http://www.surgeapp.org/',
        featured: true,
        type: 'service',
      },
      {
        id: 'S0004',
        logo: uber,
        gig: 'SherpaShare',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0005',
        logo: uber,
        gig: 'TripLog',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0006',
        logo: uber,
        gig: 'Everlance',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0030',
        logo: uber,
        gig: 'Grabb-it',
        description: 'Advertising for rideshare drivers to make more',
        indeed: '',
        promo: '',
        gigsite: 'https://grabb.io/',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0031',
        logo: uber,
        gig: 'Hurdlr',
        description: 'Mileage and expense tracker',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0032',
        logo: uber,
        gig: 'Packir',
        description: 'Delivery backpack for food',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0033',
        logo: uber,
        gig: 'Play Octopus',
        description: 'rideshare advertising and entertainment',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0034',
        logo: uber,
        gig: 'Dash Cam',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0035',
        logo: uber,
        gig: 'Home Dog Care Business: Dog Boarding, Walking & Pet Sitting',
        description:
          'Market your dog care services: pet sitting, dog walking, dog training, pet boarding & dog kennel locally with Google SEO Udemy Course for Pet Sitting Gigs',
        indeed: '',
        promo: '',
        gigsite:
          'https://www.udemy.com/course/rover-how-to-start-your-dog-walking-business-from-home',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0036',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0037',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0038',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0039',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0040',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0041',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0042',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0043',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0044',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0045',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0046',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0047',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0048',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0049',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0050',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0051',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0052',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0053',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0054',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0055',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0056',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0057',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0058',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0059',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0060',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0061',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0062',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0063',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0064',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0065',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0066',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0067',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0068',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0069',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0070',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0071',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0072',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0073',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0074',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0075',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0076',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0077',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0078',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0079',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0080',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0081',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0082',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0083',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0084',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0085',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0086',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0087',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0088',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0089',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0090',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0091',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0092',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0093',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0094',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0095',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0096',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0097',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0098',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0099',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0100',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0101',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0102',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0103',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0104',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0105',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0106',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0107',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0108',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0109',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0110',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0111',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0112',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0113',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0114',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0115',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0116',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0117',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0118',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0119',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0120',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0121',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0122',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0123',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0124',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0125',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0126',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0127',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0128',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0129',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0130',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0131',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0132',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0133',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
    ],
  },
};

/* eslint-disable default-case, no-param-reassign */
const appReducer = (state = initialState, action) =>
  produce(state, draft => {
    switch (action.type) {
      case LOAD_GIGS:
        draft.loading = true;
        draft.error = false;
        draft.userData.gigs = false;
        break;

      case LOAD_GIGS_SUCCESS:
        draft.userData.gigs = action.gigs;
        draft.loading = false;
        draft.currentUser = action.username;
        break;

      case LOAD_GIGS_ERROR:
        draft.error = action.error;
        draft.loading = false;
        break;
    }
  });

export default appReducer;
