/*
 * AppReducer
 *
 * The reducer takes care of our data. Using actions, we can
 * update our application state. To add a new action,
 * add it to the switch statement in the reducer function
 *
 */

import produce from 'immer';
import { LOAD_GIGS_SUCCESS, LOAD_GIGS, LOAD_GIGS_ERROR } from './constants';
import rlac from './img/rlac.png';
import rover from './img/rover.jpg';
import uber from './img/uber.png';
import neighbor from './img/neighbor.png';
import taskrabbit from './img/taskrabbit.png';
import thumbtack from './img/thumbtack.png';
import roadie from './img/roadie.png';
import instacart from './img/instacart.png';
import lyft from './img/lyft.png';
import amazon from './img/amazon.png';
import airbnb from './img/airbnb.png';
import graphite from './img/graphite.png';
import postmates from './img/postmates.png';
import doordash from './img/doordash.png';
import wag from './img/wag.png';
import ubereats from './img/ubereats.png';
import turo from './img/turo.png';
import getaround from './img/getaround.png';
import fiverr from './img/fiverr.png';
import handy from './img/handy.png';
// Services
import gridwise from './img/gridwise.png';
import mystro from './img/mystro.jpg';
import surge from './img/surge.png';

// The initial state of the App
export const initialState = {
  loading: false,
  error: false,
  userData: {
    gigs: [
      // Gigs
      {
        id: 'G0001',
        logo: uber,
        gig: 'Uber Driver',
        description:
          'The taxi of the 21st century. Drive around town, picking up and dropping off passengers.',
        indeed: 'https://www.indeed.com/cmp/Uber/reviews',
        promo:
          'Sign Up With Promo Code PRGREY and Get $20 When You Complete a Trip',
        gigsite: 'uber.com/drive/',
        featured: true,
        type: 'gig',
      },
      {
        id: 'G0002',
        logo: rlac,
        gig: 'Rent Like a Champion',
        description:
          'AirBnb for sporting events! Rent your home out to eager fans traveling for games in your hometown.',
        indeed: 'https://www.trustpilot.com/review/rentlikeachampion.com',
        promo:
          'Sign Up With Promo Code XXXXX and Get $20 After Your First Rental',
        gigsite: 'https://rentlikeachampion.com/',
        featured: true,
        type: 'gig',
      },
      {
        id: 'G0003',
        logo: rover,
        gig: 'Rover Walker',
        description:
          'Love animals? Get paid to watch dogs as a Sitter or walk dogs as a Walker through Rover!',
        indeed:
          'https://www.indeed.com/cmp/Rover.com/reviews?fcountry=ALL&fjobtitle=Dog+Walker',
        promo: 'Sign Up Through the Link Below and Get $20!',
        gigsite: 'http://share.rover.com/SWhzJ',
        featured: true,
        type: 'gig',
      },
      {
        id: 'G0004',
        logo: neighbor,
        gig: 'Neighbor Storage',
        description:
          'Earn money by giving your empty storage space a job. Rent out your basement, garage and even closets!',
        indeed: 'https://www.trustpilot.com/review/neighbor.com',
        promo: 'Sign Up Through the Link Below and Get $50!',
        gigsite: 'https://www.neighbor.com/invited/nextwrk-39640',
        featured: true,
        type: 'gig',
      },
      {
        id: 'G0005',
        logo: taskrabbit,
        gig: 'TaskRabbit Tasker',
        description:
          'TaskRabbit is a marketplace that matches freelance labor with local demand. Get paid to help with everyday tasks, like cleaning, moving, delivery and handyman work',
        indeed: 'https://www.indeed.com/cmp/Taskrabbit/reviews',
        promo: '',
        gigsite:
          'https://support.taskrabbit.com/hc/en-us/articles/360031918292-How-Do-I-Become-a-Tasker-',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0006',
        logo: thumbtack,
        gig: 'Thumbtack Pro',
        description:
          'Thumbtack matches customers with local professionals in categories such as home, wellness, events, and lessons.',
        indeed: 'https://www.indeed.com/cmp/Thumbtack/reviews',
        promo: '',
        gigsite:
          'https://help.thumbtack.com/article/signing-up-as-a-professional',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0007',
        logo: roadie,
        gig: 'Roadie Driver',
        description:
          'Going on a roadtrip soon? Roadie will pay you to fill your empty space and complete deliveries on the way',
        indeed: 'https://www.indeed.com/cmp/Roadie/reviews',
        promo: '',
        gigsite: 'https://my.roadie.com/drive/sign-up/basic-info',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0008',
        logo: instacart,
        gig: 'Instacart Shopper',
        description:
          'Shoppers are independent contractors that use the Instacart platform to shop and deliver orders for their customers.',
        indeed: 'https://www.indeed.com/cmp/Instacart/reviews',
        promo: '',
        gigsite: 'https://shoppers.instacart.com/',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0009',
        logo: lyft,
        gig: 'Lyft Driver',
        description:
          'Lyft is a ridesharing app. Get paid to drive passengers around town',
        indeed: 'https://www.indeed.com/cmp/Lyft/reviews',
        promo: '',
        gigsite: 'https://www.lyft.com/drive-with-lyft',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0010',
        logo: amazon,
        gig: 'Amazon Flex Driver',
        description:
          'Perform the "last mile" of Amazon delivery, moving packages from regional centers to customers.',
        indeed: 'https://www.indeed.com/cmp/Amazon.com/reviews?fcountry=ALL',
        promo: '',
        gigsite: 'https://flex.amazon.com/',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0011',
        logo: graphite,
        gig: 'Graphite Freelancer',
        description:
          'Graphite is a freelance network of 5,200 independent experts, consultants, executives and boutique firms',
        indeed: '',
        promo: '',
        gigsite: 'https://www.graphite.com/professional/signup',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0012',
        logo: airbnb,
        gig: 'AirBnB Host',
        description:
          'Rent out your home and/or rooms to travelers. AirBnB gives you full control of your availability, prices and house rules.',
        indeed: 'https://www.indeed.com/cmp/Airbnb/reviews',
        promo: '',
        gigsite: 'https://www.airbnb.com/host/homes',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0013',
        logo: postmates,
        gig: 'Postmates Courier',
        description:
          'Postmates drivers earn a living by delivering food, convenience items, and small office goods to local consumers.',
        indeed: 'https://www.indeed.com/cmp/Postmates/reviews',
        promo: '',
        gigsite: 'https://fleet.postmates.com/',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0014',
        logo: doordash,
        gig: 'DoorDash Dasher',
        description:
          'Doordash is a food delivery app that employs Dashers to Deliver goods.',
        indeed: 'https://www.indeed.com/cmp/Doordash/reviews',
        promo: '',
        gigsite: 'https://www.doordash.com/dasher/signup/',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0015',
        logo: wag,
        gig: 'Wag Walker',
        description:
          'Wag! is the #1 dog walking app to book a dog walker on-demand, or at your convenience.',
        indeed: 'https://www.indeed.com/cmp/Wag!-1/reviews',
        promo: '',
        gigsite: 'https://wagwalking.com/dog-walker',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0016',
        logo: ubereats,
        gig: 'Uber Delivery Driver',
        description:
          'UberEats drivers pick up food from local restaurants and deliver the orders to customers.',
        indeed:
          'https://www.indeed.com/cmp/Uber-Partner-Drivers/reviews?fjobtitle=Delivery+Driver',
        promo: '',
        gigsite: 'https://www.uber.com/a/signup/drive/deliver/',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0017',
        logo: turo,
        gig: 'Turo Car Rental',
        description:
          'Instead of leaving your car in the garage all day, rent it out! Turo is a car rental service that connects renters with car owners.',
        indeed: 'https://www.trustpilot.com/review/turo.com',
        promo: '',
        gigsite: 'https://turo.com/us/en/list-your-car',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0018',
        logo: getaround,
        gig: 'Getaround Car Rental',
        description:
          'Instead of leaving your car in the garage all day, rent it out! Getaround is a car rental service that connects renters with car owners.',
        indeed: 'https://www.yelp.com/biz/getaround-san-francisco',
        promo: '',
        gigsite: 'https://www.getaround.com/list',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0019',
        logo: fiverr,
        gig: 'Fiverr Freelancer',
        description:
          'Fiverr is one of the easiest ways to make money in the gig economy. No matter what skills you have, with a little creativity you sell your services to a platform of motivated buyers.',
        indeed: 'https://www.indeed.com/cmp/Fiverr/reviews',
        promo: '',
        gigsite: 'https://www.fiverr.com/start_selling',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0020',
        logo: handy,
        gig: 'Handy Worker',
        description:
          'Handy pays for being a home cleaner and handymen. It covers over 20 cities in North America, Canada, and the UK.',
        indeed: 'https://www.indeed.com/cmp/Handy/reviews',
        promo: '',
        gigsite: 'https://www.handy.com/apply',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0021',
        logo: uber,
        gig: 'Wonolo',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0022',
        logo: uber,
        gig: 'Bellhops',
        description:
          'Get paid to pack boxes and move people into their new digs.',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0023',
        logo: uber,
        gig: 'Care.com',
        description:
          'Primarily a place to find work in child or pet care, Care.com also offers gigs for housekeepers, gardeners, tutors, and those caring for the elderly.',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0024',
        logo: uber,
        gig: 'Caviar',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0025',
        logo: uber,
        gig: 'Closet Collective',
        description:
          'Are you a fashionista with a closet full of designer clothes? If so, Closet Collective will provide the venue for renting your $200 plus designer pieces.',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0026',
        logo: uber,
        gig: 'CrowdFlower',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0027',
        logo: uber,
        gig: 'Dolly',
        description:
          'The Dolly service uses people that have vehicles for moving, or movers to do the heavy lifting if they don’t have a vehicle. ',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0028',
        logo: uber,
        gig: 'Etsy',
        description:
          'Etsy provides a marketplace for people to sell their handmade, vintage, or creative goods online.',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0029',
        logo: uber,
        gig: 'Fancy Hands',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0030',
        logo: uber,
        gig: 'Favor',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0031',
        logo: uber,
        gig: 'Feastly',
        description:
          'If you are a chef and want to host meals and you are a foodie looking for great chef, Feastly is a platform that brings them both together. ',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0032',
        logo: uber,
        gig: 'Freelancer',
        description:
          'Freelancer has posted almost 11 million jobs for tens of thousands of its members. ',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0033',
        logo: uber,
        gig: 'Gigwalk',
        description:
          'Work for Gigwalk usually involves gathering data for companies about their products and stores. For example, you might be checking what’s on the shelves in a particular shop, and whether it’s correctly priced and labeled.',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0034',
        logo: uber,
        gig: 'Grubhub',
        description:
          'A food delivery service, similar to DoorDash and other options on this website.',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0035',
        logo: uber,
        gig: 'HelloTech',
        description:
          'HelloTech gives experts in the tech industry a platform to provide services for individuals in their homes and businesses. ',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0036',
        logo: uber,
        gig: 'HomeAway',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0037',
        logo: uber,
        gig: 'HopSkipDrive',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0038',
        logo: uber,
        gig: 'Hubstaff Talent',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0039',
        logo: uber,
        gig: 'Juno',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0040',
        logo: uber,
        gig: 'Moonlighting',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0041',
        logo: uber,
        gig: 'onefinestay',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0042',
        logo: uber,
        gig: 'OpenAirplane',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0043',
        logo: uber,
        gig: 'PeoplePerHour',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0044',
        logo: uber,
        gig: 'Prefer',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0045',
        logo: uber,
        gig: 'Rentah',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0046',
        logo: uber,
        gig: 'Shipt',
        description:
          'Delivering groceries, home products, and some electronics for a company owned by Target.',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0047',
        logo: uber,
        gig: 'Snagajob',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0048',
        logo: uber,
        gig: 'Spare5',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0049',
        logo: uber,
        gig: 'SpotHero',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0050',
        logo: uber,
        gig: 'Takl',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0051',
        logo: uber,
        gig: 'TaskEasy',
        description:
          'TaskEasy freelancers offer lawnmowing, gardening, and landscaping services.',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0052',
        logo: uber,
        gig: 'Upwork',
        description:
          'Upwork connects freelancers with hundreds of thousands of clients in numerous niches. From photography to customer service to interior design, there’s hardly a limit on the types of jobs you can find on Upwork. Like other freelance job sites, Upwork charges a fee for its services. Expect to pay up to 20% of your earnings to the platform on each job you complete.',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0053',
        logo: uber,
        gig: 'VRBO',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0054',
        logo: uber,
        gig: 'Wingz',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0055',
        logo: uber,
        gig: 'YourMechanic',
        description:
          'Providing car repairs and maintenance carried out at customers’ homes, YourMechanic is a way for people with auto repair skills to leverage the gig economy.',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0056',
        logo: uber,
        gig: 'Zeel',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0057',
        logo: uber,
        gig: 'ToolLocker',
        description:
          'Whether you have light or heavy equipment, ToolLocker lets you rent them with a great user interface that filters equipment by category, availability, location and more.',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0058',
        logo: uber,
        gig: 'ParkingPanda',
        description:
          'A parking space is a premium product in many major cities across the country. ParkingPanda is an app that brings owners and customers together seamlessly. You can post a free listing with the app to start earning cash whenever anyone books your space.',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0059',
        logo: uber,
        gig: 'Udemy',
        description:
          'Udemy has more than 45,000 courses taught by expert instructors in a wide range of subjects. If you want to earn money from your expertise, you can create your video lesson and post it on Udemy.',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0060',
        logo: uber,
        gig: 'LinkedIn ProFinder',
        description:
          'LinkedIn ProFinder connects top freelance professionals like you with high quality leads.',
        indeed: '',
        promo: '',
        gigsite: 'https://www.linkedin.com/profinder/pros',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0061',
        logo: uber,
        gig: 'Helpr',
        description:
          'An app that connects parents with reliable childcare help (i.e., babysitting), Helpr is ideal for those with relevant experience looking for occasional part-time work.',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0062',
        logo: uber,
        gig: 'VIPKid',
        description:
          'VIPKid is an online portal through which English language tutors around the world teach pupils (primarily in China).',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0063',
        logo: uber,
        gig: '99 Designs',
        description:
          'A company that provides graphic design services, ranging from book covers to company logos.',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0064',
        logo: uber,
        gig: 'Soothe',
        description:
          'Gig work for massage therapists, including deep tissue, sports, and couples massage work. ',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0065',
        logo: uber,
        gig: 'Guru',
        description:
          'Another site for freelancing professionals, covering everything from writing to marketing to legal advice. Like Upwork, it allows you to work for people all around the world without moving from your desk.',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0066',
        logo: uber,
        gig: 'RVShare',
        description: 'A site that lets you rent out your RV',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0067',
        logo: uber,
        gig: 'Boatsetter',
        description:
          'If you own a boat, then Boatsetter lets you rent it out — either with or without a captain.',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0068',
        logo: uber,
        gig: 'Printed Village',
        description:
          'Printed Village is a fabric design company. As a designer, you earn a commission on products that choose your design.',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0069',
        logo: uber,
        gig: 'Secret Shopper',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0070',
        logo: uber,
        gig: 'Market Force',
        description:
          'At Market Force, you’ll complete mystery shops for banks, restaurants, and stores in order to help those businesses thrive.',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0071',
        logo: uber,
        gig: 'GBW',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0072',
        logo: uber,
        gig: 'Pinnacle',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0073',
        logo: uber,
        gig: 'A Closer Look',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0074',
        logo: uber,
        gig: 'Quest for the Best',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0075',
        logo: uber,
        gig: 'Intellishop',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0076',
        logo: uber,
        gig: 'Perception Strategies',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0077',
        logo: uber,
        gig: 'Sinclair Customer Metrics',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0078',
        logo: uber,
        gig: 'Call Center QA',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0079',
        logo: uber,
        gig: 'ARC Consulting',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0142',
        logo: uber,
        gig: 'Veryable',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0143',
        logo: uber,
        gig: 'Skipcart',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0144',
        logo: uber,
        gig: 'Hungr',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0145',
        logo: uber,
        gig: 'Skooli',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0146',
        logo: uber,
        gig: 'Literably',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0147',
        logo: uber,
        gig: 'Census Taker',
        description: '',
        indeed: '',
        promo: '',
        gigsite:
          'https://recruitment.2020census.gov/ats/careersite/createprofilelite.aspx?c=census&site=1',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0148',
        logo: uber,
        gig: 'Zifty Driver',
        description: '',
        indeed: '',
        promo: '',
        gigsite: 'http://jobs.zifty.com/',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0149',
        logo: uber,
        gig: 'LawnStarter',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0150',
        logo: uber,
        gig: 'Plowz and Mowz',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0151',
        logo: uber,
        gig: 'GoShare Delivery',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0152',
        logo: uber,
        gig: 'Lawn Love',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0153',
        logo: uber,
        gig: 'Bird Scooter Charger',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0154',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0155',
        logo: uber,
        gig: 'PICKUP',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0156',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0157',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0158',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0159',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0160',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0161',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0162',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0163',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0164',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0165',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0166',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0167',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0168',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0169',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0170',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0171',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0172',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0173',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0174',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0175',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0176',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0177',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0178',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0179',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0180',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0181',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0182',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0183',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0184',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0185',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0186',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0187',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0188',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0189',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0190',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0191',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0192',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0193',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0194',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },
      {
        id: 'G0195',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'gig',
      },

      // Services
      {
        id: 'S0001',
        logo: gridwise,
        gig: 'Gridwise',
        description:
          'Gridwise is an intelligence platform which provides information on ridesharing insights to customers, including both rideshare and taxi drivers, to help drivers improve efficiency and profits on the road.',
        indeed:
          'https://appgrooves.com/app/gridwise-earn-more-by-driving-smarter-by-swerv-technologies-llc/negative',
        promo: '',
        gigsite: 'https://gridwise.io/',
        featured: true,
        type: 'service',
      },
      {
        id: 'S0002',
        logo: mystro,
        gig: 'Mystro',
        description:
          'Mystro is an app that orchestrates incoming passenger requests between the Uber and Lyft rideshare apps, so you can stop clicking back and forth',
        indeed:
          'https://play.google.com/store/apps/details?id=partners.driver.mystro&hl=en_US',
        promo: '',
        gigsite: 'https://mystrodriver.com/download',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0003',
        logo: surge,
        gig: 'Surge 2x',
        description:
          'By using Surge you are able to only drive during surges. You will be able to out perform other top drivers in your city, drastically increasing your profit.',
        indeed: 'https://apps.apple.com/us/app/surge-2x/id986581500',
        promo: '',
        gigsite: 'http://www.surgeapp.org/',
        featured: true,
        type: 'service',
      },
      {
        id: 'S0004',
        logo: uber,
        gig: 'SherpaShare',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0005',
        logo: uber,
        gig: 'TripLog',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0006',
        logo: uber,
        gig: 'Everlance',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0030',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0031',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0032',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0033',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0034',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0035',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0036',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0037',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0038',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0039',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0040',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0041',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0042',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0043',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0044',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0045',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0046',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0047',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0048',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0049',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0050',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0051',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0052',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0053',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0054',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0055',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0056',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0057',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0058',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0059',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0060',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0061',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0062',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0063',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0064',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0065',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0066',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0067',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0068',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0069',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0070',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0071',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0072',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0073',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0074',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0075',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0076',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0077',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0078',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0079',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0080',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0081',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0082',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0083',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0084',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0085',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0086',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0087',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0088',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0089',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0090',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0091',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0092',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0093',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0094',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0095',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0096',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0097',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0098',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0099',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0100',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0101',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0102',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0103',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0104',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0105',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0106',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0107',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0108',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0109',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0110',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0111',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0112',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0113',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0114',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0115',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0116',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0117',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0118',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0119',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0120',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0121',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0122',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0123',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0124',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0125',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0126',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0127',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0128',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0129',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0130',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0131',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0132',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
      {
        id: 'S0133',
        logo: uber,
        gig: '',
        description: '',
        indeed: '',
        promo: '',
        gigsite: '',
        featured: false,
        type: 'service',
      },
    ],
  },
};

/* eslint-disable default-case, no-param-reassign */
const appReducer = (state = initialState, action) =>
  produce(state, draft => {
    switch (action.type) {
      case LOAD_GIGS:
        draft.loading = true;
        draft.error = false;
        draft.userData.gigs = false;
        break;

      case LOAD_GIGS_SUCCESS:
        draft.userData.gigs = action.gigs;
        draft.loading = false;
        draft.currentUser = action.username;
        break;

      case LOAD_GIGS_ERROR:
        draft.error = action.error;
        draft.loading = false;
        break;
    }
  });

export default appReducer;
